(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DES_V_X-VAL
          DES_V_X
          DES_V_Y-VAL
          DES_V_Y
          DES_V_Z-VAL
          DES_V_Z
          FB_A_X-VAL
          FB_A_X
          FB_A_Y-VAL
          FB_A_Y
          FB_A_Z-VAL
          FB_A_Z
          DES_A_X-VAL
          DES_A_X
          DES_A_Y-VAL
          DES_A_Y
          DES_A_Z-VAL
          DES_A_Z
          DES_Q_X-VAL
          DES_Q_X
          DES_Q_Y-VAL
          DES_Q_Y
          DES_Q_Z-VAL
          DES_Q_Z
          DES_Q_W-VAL
          DES_Q_W
          DES_THR-VAL
          DES_THR
          HOVER_PERCENTAGE-VAL
          HOVER_PERCENTAGE
          THR_SCALE_COMPENSATE-VAL
          THR_SCALE_COMPENSATE
          VOLTAGE-VAL
          VOLTAGE
          ERR_AXISANG_X-VAL
          ERR_AXISANG_X
          ERR_AXISANG_Y-VAL
          ERR_AXISANG_Y
          ERR_AXISANG_Z-VAL
          ERR_AXISANG_Z
          ERR_AXISANG_ANG-VAL
          ERR_AXISANG_ANG
          FB_RATE_X-VAL
          FB_RATE_X
          FB_RATE_Y-VAL
          FB_RATE_Y
          FB_RATE_Z-VAL
          FB_RATE_Z
))